version: "3.8"

services:
  portfolio-dev:
    container_name: portfolio_dev
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

  portfolio-prod:
    container_name: portfolio_prod
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production

  portfolio-build:
    container_name: portfolio_build
    build:
      context: .
      dockerfile: Dockerfile
      target: build